d

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,12 +45,12 @@ jobs:
         shell: bash
 
       - name: Compile contracts
-        run: npm -s run prepack:all
+        run: npm -s run prepack
 
       - name: Deploy all contracts
         run: |
           for dir in contracts/*/; do
             CONTRACT=$(basename $dir)
             echo "🚀 Producing $CONTRACT..."
-            CONTRACT=$CONTRACT npm -s run produce || { echo "❌ Deployment failed for $CONTRACT"; exit 1; }
+            CONTRACT=$CONTRACT npm -s run contract:produce || { echo "❌ Deployment failed for $CONTRACT"; exit 1; }
           done
